wget http://nehe.gamedev5.net/data/lessons/devc/lesson01.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson02.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson03.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson04.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson05.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson06.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson07.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson08.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson09.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson10.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson11.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson12.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson13.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson14.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson15.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson16.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson17.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson18.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson19.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson20.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson21.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson22.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson23.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson24.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson25.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson26.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson27.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson28.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson29.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson30.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson31.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson32.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson33.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson34.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson35.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson36.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson37.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson38.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson39.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson40.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson41.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson42.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson43.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson44.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson45.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson46.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson47.zip
wget http://nehe.gamedev5.net/data/lessons/devc/lesson48.zip
