######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 22 10:47:31 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += aclock.h
SOURCES += aclock.cpp main.cpp
