wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson01.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson02.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson03.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson04.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson05.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson06.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson07.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson08.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson09.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson10.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson11.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson12.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson13.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson14.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson15.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson16.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson17.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson18.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson19.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson20.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson21.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson22.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson23.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson24.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson25.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson26.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson27.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson28.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson29.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson30.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson31.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson32.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson33.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson34.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson35.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson36.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson37.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson38.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson39.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson40.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson41.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson42.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson43.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson44.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson45.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson46.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson47.tar.gz
wget http://nehe.gamedev5.net/data/lessons/qt_cpp/lesson48.tar.gz
