######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 26 16:08:57 2007
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += test_execle.cpp
