wget http://nehe.gamedev5.net/data/lessons/vc/lesson01.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson02.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson03.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson04.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson05.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson06.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson07.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson08.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson09.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson10.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson11.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson12.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson13.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson14.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson15.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson16.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson17.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson18.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson19.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson20.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson21.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson22.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson23.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson24.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson25.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson26.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson27.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson28.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson29.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson30.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson31.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson32.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson33.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson34.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson35.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson36.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson37.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson38.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson39.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson40.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson41.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson42.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson43.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson44.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson45.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson46.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson47.zip
wget http://nehe.gamedev5.net/data/lessons/vc/lesson48.zip
