wget http://nehe.gamedev5.net/data/lessons/linux/lesson01.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson02.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson03.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson04.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson05.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson06.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson07.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson08.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson09.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson10.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson11.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson12.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson13.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson14.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson15.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson16.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson17.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson18.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson19.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson20.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson21.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson22.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson23.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson24.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson25.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson26.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson27.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson28.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson29.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson30.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson31.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson32.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson33.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson34.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson35.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson36.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson37.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson38.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson39.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson40.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson41.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson42.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson43.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson44.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson45.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson46.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson47.tar.gz
wget http://nehe.gamedev5.net/data/lessons/linux/lesson48.tar.gz
