document.writeln("<table width=\"948\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td width=\"51\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/www.ccidnet.com\/\" target=\"_blank\" class=\"a22\">首　页<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"60\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/news.ccidnet.com\/\" target=\"_blank\" class=\"a22\">资讯中心<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"65\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/comm.ccidnet.com\/\" target=\"_blank\" class=\"a22\">通信产业<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"52\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/product.ccidnet.com\/\" target=\"_blank\" class=\"a22\">IT产品<\/a><a href=\"#\" target=\"_blank\"><\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"51\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/tech.ccidnet.com\/\" target=\"_blank\" class=\"a22\">IT技术<\/a><a href=\"#\" target=\"_blank\"><\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"51\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/industry.ccidnet.com\/\" target=\"_blank\" class=\"a22\">信息化<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"40\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/bbs.ccidnet.com\/\" target=\"_blank\" class=\"a22\">社区<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"40\" align=\"center\" valign=\"bottom\"><a href=\"http:\/\/blog.ccidnet.com\/\" target=\"_blank\" class=\"a22\">博客<\/a><\/td>");
document.writeln("    <td valign=\"bottom\" align=\"center\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"230\" align=\"center\" valign=\"bottom\"><table width=\"220\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("      <tr>");
document.writeln("        <td align=\"center\" class=\"a22\">·<a href=\"http:\/\/market.ccidnet.com\/\" target=\"_blank\" class=\"a22\">情报中心<\/a><\/td>");
document.writeln("        <td align=\"center\"><span class=\"a22\">·<a href=\"http:\/\/education.ccidnet.com\/\" target=\"_blank\" class=\"a22\">赛迪网校<\/a><\/span><\/td>");
document.writeln("        <td align=\"center\"><span class=\"a22\">·<a href=\"http:\/\/media.ccidnet.com\/\" target=\"_blank\" class=\"a22\">赛迪媒体<\/a><\/span><\/td>");
document.writeln("        <td align=\"center\"><span class=\"a22\"><font color=\"red\">·</font><a href=\"http:\/\/2008.ccidnet.com\/\" target=\"_blank\" class=\"a22\"><font color=\"red\">奥运</font><\/a><\/span><\/td>");
document.writeln("      <\/tr>");
document.writeln("    <\/table><\/td>");
document.writeln("    <td valign=\"bottom\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("    <td width=\"168\" align=\"center\" valign=\"bottom\"><table width=\"172\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("      <tr>");
document.writeln("        <td align=\"center\" class=\"a22\">[<a href=\"http:\/\/chat.ccidnet.com\/\" target=\"_blank\" class=\"a22\">访谈<\/a>]<\/td>");
document.writeln("        <td align=\"center\" class=\"a22\">[<a href=\"http:\/\/news.ccidnet.com\/col\/999\/999.html\" target=\"_blank\" class=\"a22\">直播<\/a>]<\/td>");
document.writeln("        <td align=\"center\" class=\"a22\">[<a href=\"http:\/\/register.ccidnet.com\/passport\/myccid\/mystatus\" target=\"_blank\" class=\"a22\">直邮<\/a>]<\/td>");
document.writeln("        <td align=\"center\" class=\"a22\">[<a href=\"http:\/\/consult.ccidnet.com\/\" target=\"_blank\" class=\"a22\">调查<\/a>]<\/td>");
document.writeln("      <\/tr>");
document.writeln("    <\/table><\/td>");
document.writeln("    <td valign=\"bottom\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/wz_line1.jpg\" width=\"1\" height=\"21\" \/><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>")