document.writeln('<iframe src="http://image.ccidnet.com/nav/aleax_counts.htm" height="0" width="0"></iframe>');
document.writeln('<iframe src="http://image.ccidnet.com/ad_files/home_daohang/copyright_20040226_07.htm" height="0" width="0"></iframe>');
document.writeln("<table width=\"760\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\">");
document.writeln("	<a href=\"http:\/\/www.ccidnet.com\/\" target=\"_blank\" class=\"a21\">返回主页<\/a> ");
document.writeln("	<span class=\"a21\">|<\/span> ");
document.writeln("	<a href=\"http:\/\/image.ccidnet.com\/help\/webmap.html\" target=\"_blank\" class=\"a21\">网站地图<\/a> ");
document.writeln("	<span class=\"a21\">|<\/span> ");
document.writeln("	<a href=\"http:\/\/image.ccidnet.com\/help\/aboutus.html\" target=\"_blank\" class=\"a21\">关于我们<\/a> ");
document.writeln("	<span class=\"a21\">|<\/span> ");
document.writeln("	<a href=\"http:\/\/register.ccidnet.com\/passport\/service\/agreement.htm\" target=\"_blank\" class=\"a21\">新用户注册<\/a> ");
document.writeln("	<span class=\"a21\">|<\/span> ");
document.writeln("	<a href=\"http:\/\/search.ccidnet.com\/\" target=\"_blank\" class=\"a21\">网站检索<\/a> ");
document.writeln("	<span class=\"a21\">|<\/span> ");
document.writeln("	<a href=\"mailto:ad@staff.ccidnet.com\" target=\"_blank\" class=\"a21\">联系广告<\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\">联系我们：<a href=\"mailto:webmaster@staff.ccidnet.com\" target=\"_blank\" class=\"a22\">webmaster@staff.ccidnet.com<\/a> Tel:8610-88558942 <br \/>");
document.writeln("      广告发布：<a href=\"mailto:ad@staff.ccidnet.com\" target=\"_blank\" class=\"a22\">ad@staff.ccidnet.com<\/a> Tel:8610-88558949&nbsp;8610-88558951 <br \/>");
document.writeln("      方案、案例展示：<a href=\"mailto:project@staff.ccidnet.com\" target=\"_blank\" class=\"a22\">project@staff.ccidnet.com<\/a> Tel:8610-88558927 <br \/>");
document.writeln("      产品经销商合作：<a href=\"mailto:qudao@staff.ccidnet.com\" target=\"_blank\" class=\"a22\">qudao@staff.ccidnet.com<\/a> Tel:8610-88558912 88558924-1012/1008/ <br \/>");
document.writeln("      <a href=\"http:\/\/image.ccidnet.com\/help\/copyright.htm\" target=\"_blank\" class=\"a22\">Copyright 2000-2007 CCIDnet.All rights reserved.<\/a> <br \/>");
document.writeln("      京ICP000080号 网站-3 <a href=\"http:\/\/www.hd315.gov.cn\/beian\/view.asp?bianhao=0102000111400011\" target=\"_blank\"><img src=\"http:\/\/www.ccidnet.com\/images\/homepage\/315.gif\" width=\"40\" height=\"48\" border=\"0\" align=\"absmiddle\" \/><\/a> ");
document.writeln("    <\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>")
