wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson01.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson02.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson03.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson04.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson05.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson06.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson07.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson08.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson09.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson10.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson11.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson12.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson13.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson14.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson15.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson16.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson17.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson18.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson19.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson20.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson21.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson22.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson23.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson24.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson25.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson26.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson27.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson28.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson29.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson30.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson31.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson32.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson33.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson34.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson35.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson36.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson37.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson38.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson39.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson40.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson41.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson42.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson43.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson44.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson45.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson46.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson47.zip
wget http://nehe.gamedev5.net/data/lessons/vs_net/lesson48.zip
