DISQUS.addBlocks("theme")(function(c){c.blocks.letUsKnow=function(j,d){var a=new c.Builder,i=DISQUS.extend({},j,d);with(i)return a.put('<a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">'),a.put(gettext("Let us know.")),a.put("</a>"),a.compile()};c.blocks.relatedThread=function(j,d){var a=new c.Builder,i=DISQUS.extend({},j,d);with(i)return a.put('    <li class="discovery-unit">        <div class="discovery-heading-wrapper">            <h3 title="'),a.put((a.esc||function(a){return a})(thread.title)),
a.put('">                <a data-role="discovery-thread-title" class="title publisher-anchor-color" '),function(){var e={};c.extend(e,d);c.extend(e,{});a.put(c.renderBlock("linkAttributes",e))}(),a.put(">                    "),a.put(thread.title),a.put('                </a>            </h3>        </div>        <ul class="meta">            <li class="comments">                <a '),function(){var e={};c.extend(e,d);c.extend(e,{});a.put(c.renderBlock("linkAttributes",e))}(),a.put(">                "),
thread.posts===1?(a.put("                    "),a.put(gettext("1 comment")),a.put("                ")):thread.posts>=0&&(a.put("                    "),a.put(c.interpolate(gettext("%(numPosts)s comments"),{numPosts:thread.posts})),a.put("                ")),a.put('                </a>            </li>            <li class="time">'),a.put((a.esc||function(a){return a})(thread.createdAgo)),a.put('</li>        </ul>        <a class="top-comment" '),function(){var e={};c.extend(e,d);c.extend(e,{});a.put(c.renderBlock("linkAttributes",
e))}(),a.put(' data-role="discovery-top-comment">            <img src="'),a.put((a.esc||function(a){return a})(urls.avatar.generic)),a.put('" alt="'),a.put(gettext("Default user")),a.put('" data-role="discovery-avatar">            <p><span class="user" data-role="discovery-top-comment-author">'),a.put('</span> &#8212; <span data-role="discovery-top-comment-snippet">'),a.put("</span></p>        </a>    </li>"),a.compile()};c.blocks.linkAttributes=function(j,d){var a=new c.Builder,i=DISQUS.extend({},
j,d);with(i)return a.put('href="'),a.put((a.esc||function(a){return a})(thread.link)),a.put('#disqus_thread" data-redirect="'),a.put((a.esc||function(a){return a})(thread.redirectUrl)),a.put('"'),a.compile()};c.blocks.relatedThreads=function(j,d){var a=new c.Builder,i=DISQUS.extend({},j,d);with(i)return a.put('<div id="discovery-main">    <div id="discovery-note" style="display:none;">        <div class="alert">            '),a.put(c.interpolate(gettext("The new DISQUS Discovery box helps you find other vibrant discussions on the communities you love. Feedback? %(letUsKnow)s"),
{letUsKnow:c.renderBlock("letUsKnow")})),a.put('        </div>    </div>    <header>        <div id="discovery-options">            <span class="publisher-anchor-color"><a href="#" id="discovery-help" data-action="discovery-help">'),a.put(gettext("What's this?")),a.put('</a></span>            <a href="#" id="discovery-close" data-action="discovery-close" title="'),a.put(gettext("Close this box")),a.put('">\u00d7</a>        </div>        <h2>'),a.put(c.interpolate(gettext("Also on %(forumName)s"),
{forumName:c.renderBlock("forumName",forum)})),a.put('</h2>    </header>    <section>        <ul id="discovery-units">            '),a.put("        </ul>    </section></div>"),a.compile()};c.blocks.forumName=function(j,d){var a=new c.Builder,i=DISQUS.extend({},j,d);with(i)return a.put("<strong>"),a.put((a.esc||function(a){return a})(name)),a.put("</strong>"),a.compile()}});
(function(c){var j=c.document,d=c.DISQUS;d.registerActions=function(){d.define("discovery.collections",function(){return{load:function(a,c){var e=d.discovery.collections;e.RelatedThreadCollection=Backbone.Collection.extend({model:a.RelatedThread,url:function(){return d.api.getURL("discovery/listRelated.json")},initialize:function(a,b){this.mainThread=b.thread;this.limit=b.limit;this.variant=b.variant},fetch:function(a){var b={};b.data={thread:this.mainThread.get("id")};b.parse=!1;_.extend(b,a);Backbone.Collection.prototype.fetch.call(this,
b)},addBandit:function(a){if((a=a.response)&&a.bandit)this.bandit=a.bandit},getBanditJSON:_.memoize(function(){return d.JSON.stringify(this.bandit)}),parse:function(a){this.addBandit(a);var b=[],g=a.response||[];if(g.results)g=g.results;var e=c.log;e("Results (",g.length,"):",g);for(var f=0,j=g.length;f<j&&b.length<this.limit;f++)if(a=g[f].thread||g[f],a.id!=this.mainThread.id)if(a.forum.id!=this.mainThread.get("forum").id)e("Thread",a.id,"does not have same forum (",a.forum.id,") as source thread's:",
this.mainThread.get("forum").id);else if(a.posts===0)e("Thread",a.id,"does not have any comments.");else if(a.title.indexOf("http://")===0)e("Thread",a.id,"has a title that starts with http.");else{var m=g[f].signedUrl?"http://redirect.disqus.com/url":a.link+"#redirect",q={url:g[f].signedUrl,thread:a.id,forum:_.isObject(a.forum)?a.forum.id:a.forum,zone:"internal_discovery",imp:d.juggler.impId,source_thread_id:this.mainThread.id};if(this.bandit)q.bandit=this.getBanditJSON();if(this.variant)q.variant=
this.variant;a.redirectUrl=d.serialize(m,q);a.score={score:g[f].score,k:g[f].k};b.push(a)}e("Total results:",b.length);return b}});return e}}});d.define("discovery",function(){return this.overwrites({init:function(a,c){function e(e){k("discovery_next:dark_promoted",function(){f("Initiating dark request to discovery/listPromoted");d.api.call("discovery/listPromoted.json",{data:{thread:a.thread.id}})});o.mainThread=e;o.fetch({success:h,error:b});o.on("error",b)}function h(h){if(h.length<2)return void b({display:!1});
h.length%2===1&&h.pop();h=new w({el:j.getElementById(a.containerId),collection:h,snippetLimit:l});c(h);b({display:!0})}function b(h){h=h||{};if(!u){u=!0;var b=d.juggler.client("juggler");if(b){var e={major_version:"next_internal",internal_organic:o.length,external_organic:0,promoted:0,display:!!h.display};o.bandit&&_.extend(e,{bandit:d.JSON.stringify(o.bandit)});a.isExperiment&&_.extend(e,{variant:a.variant});f("Juggler init_discovery",e);b.emit("init_discovery",e);k("dark_jester",function(){d.juggler.client("jester",
!0).emit("init_discovery",e)})}}}var g=d.discovery.helpers,k=g.ifSwitch,f=g.log;g.config(a.switches);var l=100,m=d.discovery.models.load(),q=d.discovery.collections.load(m,g),g=d.discovery.views.load(g),m=m.Thread,w=g.RelatedThreadCollectionView,o=new q.RelatedThreadCollection(null,{limit:4,variant:!!a.isExperiment&&a.variant});a.threadId?(f("Discovery: Making call to threads/details"),(new m).fetch({data:{thread:a.threadId,forum:a.forum,related:"forum"},success:e})):e(new m(_.extend(a.thread,{forum:a.forum})));
var u=!1}})});d.define("discovery.helpers",function(a,c){var e=null,h=!1,b=!1,g=function(){};a.console&&(g=function(){b&&(a.console.log.apply?a.console.log.apply(a.console,arguments):a.console.log(_.toArray(arguments).join(" ")))});var k=function(a){if(a===c)return b;b=!!a},f=function(a){if(a===c)return h;h=!!a},l=function(a,h,b){if(e)if(e.length)e.enabled(a)&&h();else{var d=function(){e.enabled(a)&&h();b&&e.off("reset",d)};return void e.on("reset",d)}};return{config:function(a){e=a;f(!0);l("discovery_next:logging",
function(){k(!0)})},allowLog:k,ifSwitch:l,log:g,allowLineTruncate:f,lineTruncate:function(b,e){function c(){return k.scrollHeight-k.offsetHeight>0.2*l}function g(){f.lastChild&&!_.contains(["...","\u2026"],f.lastChild.nodeValue)&&(r=f.appendChild(a.document.createTextNode(" "+s)),c()&&(f.removeChild(r),f.removeChild(f.lastChild),g()))}if(h){var i=d.logError||function(){};if(!b.closest("body").length)return void i("lineTruncate called on el not on DOM");if(b.text().length<1)return void i("lineTruncated called on empty el");
if(_.any(b.children(),function(a){return a.nodeType!==3}))return void i("lineTruncate called on non-flat el");var f=b[0],k=f;if(b.css("display")!=="block")for(;k.parentNode;)if(k=k.parentNode,$(k).css("display")==="block")break;var l=parseFloat(b.css("font-size"),10);if(c()){var e=e||{},i=e.lines||1,s=e.ellipsis,r,n=b.text();if(n.length){var t=b.width()/l,i=parseInt(t*i,10),n=n.split(/\s/),t=0;b.empty();for(var p=0,v=n.length;p<v;p++){t+=n[p].length+1;if(t>=i)break;f.appendChild(j.createTextNode(" "+
n[p]))}if(c()){do r=f.removeChild(f.lastChild);while(c())}else{do r=f.appendChild(j.createTextNode(" "+n[p++]));while(!c()&&p<v);f.removeChild(r)}s&&(_.isString(s)||(s="\u2026"),g())}}}}}});d.define("discovery.models",function(){return{load:function(){var a=d.discovery.models,c=a.Thread=Backbone.Model.extend({defaults:{author:null,category:null,createdAt:null,forum:null,identifiers:[],ipAddress:null,isClosed:!1,isDeleted:!1,link:null,message:null,slug:null,title:null,userSubscription:!1,posts:0,reactions:0,
likes:0,dislikes:0,userScore:0},url:d.api.getURL("threads/details"),parse:function(a){return a.response}});a.RelatedThread=c.extend({defaults:_.extend({},c.prototype.defaults,{redirectUrl:null,topComment:null})});return a}}});d.define("discovery.views",function(){return{load:function(a){var c=d.discovery.views,e=c.RelatedThreadView=Backbone.View.extend({events:{"click [data-redirect]":"swapLink"},dtplBlock:"relatedThread",initialize:function(a){this.snippetLimit=a.snippetLimit;this.model.on("change:topComment",
this.renderTopComment,this)},swapLink:function(a){a=a.target||a.srcElement;a.tagName.toUpperCase()=="A"&&a.getAttribute("data-redirect")||(a=$(a).closest("a[data-redirect]")[0]);var b=a;b.setAttribute("data-href",b.getAttribute("href"));b.setAttribute("href",b.getAttribute("data-redirect"));_.delay(function(){b.setAttribute("href",b.getAttribute("data-href"))},100)},renderAvatar:function(a){var b=this.$el.find("[data-role=discovery-avatar]");b.attr("src",a.avatar.cache);b.attr("alt",this.authorName(a));
return this},authorName:function(a){return a.name||a.username},renderCommentSnippet:function(c){var b=this.$el.find("[data-role=discovery-top-comment]");if(c.author){var d=this.authorName(c.author);b.find("[data-role=discovery-top-comment-author]").text(d)}c=_.strip(c.message);c=_.truncate(c,this.snippetLimit,"\u2026");d=b.find("[data-role=discovery-top-comment-snippet]");d.text(c);b.css({display:"block"});a.lineTruncate(d,{lines:3,ellipsis:!0});return this},renderTopComment:function(a,b){this.renderAvatar(b.author);
this.renderCommentSnippet(b);this.trigger("resize");return this},truncateHeading:function(){var c=this.$el.find("[data-role=discovery-thread-title]");a.lineTruncate(c,{lines:2,ellipsis:!0})},render:function(){this.setElement(d.renderBlock(this.dtplBlock,{thread:_.extend(this.model.toJSON(),{createdAgo:moment(d.assureOffset(this.model.get("createdAt")),d.ISO_8601).fromNow()})}));return this}});c.RelatedThreadCollectionView=Backbone.View.extend({events:{"click [data-action=discovery-close]":"close",
"click [data-action=discovery-help]":"showHelp"},dtplBlock:"relatedThreads",initialize:function(a){this.snippetLimit=a.snippetLimit},close:function(a){a.preventDefault();this.remove();this.trigger("resize",0)},showHelp:function(a){a.preventDefault();$(a.currentTarget).hide();this.$el.find("#discovery-note").show();this.trigger("resize")},getTopComment:function(a){var b=this;d.api.call("discovery/listTopPost.json",{method:"GET",data:{thread:a},success:function(a){a.response.length!==0&&_.each(a.response,
function(a){b.collection.get(a.thread).set("topComment",a)})}});return b},resize:_.debounce(function(){this.trigger("resize")},500),render:function(){this.$el.append(d.renderBlock(this.dtplBlock,{forum:this.collection.mainThread.get("forum")}));var a=[];this.collection.each(function(b){b=new e({model:b,snippetLimit:this.snippetLimit});a.push(b);b.on("resize",this.resize,this);b.render();this.$el.find("section > ul").append(b.el)},this);_.each(a,function(a){a.truncateHeading()});this.getTopComment(this.collection.pluck("id"));
return this}});return c}}})};d.runThemeScript=d.registerActions})(this);