/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RTEST 0x12345
#define RTESTVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define TESTVOID 1
extern  int * testvoid_1(void *, CLIENT *);
extern  int * testvoid_1_svc(void *, struct svc_req *);
#define TESTSTRING 2
extern  int * teststring_1(char **, CLIENT *);
extern  int * teststring_1_svc(char **, struct svc_req *);
extern int rtest_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TESTVOID 1
extern  int * testvoid_1();
extern  int * testvoid_1_svc();
#define TESTSTRING 2
extern  int * teststring_1();
extern  int * teststring_1_svc();
extern int rtest_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
