/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define STRINGNUM 6

#define HELLOWORLDPROG 0x30090900
#define HELLOWORLDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUESTMESSAGE 1
extern  char ** requestmessage_1(int *, CLIENT *);
extern  char ** requestmessage_1_svc(int *, struct svc_req *);
extern int helloworldprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUESTMESSAGE 1
extern  char ** requestmessage_1();
extern  char ** requestmessage_1_svc();
extern int helloworldprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
