######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 16 15:47:19 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cube.h GLFun.h
SOURCES += cube.cpp main.cpp
