######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 22 10:30:19 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myClass1.h myClass2.h
SOURCES += exMoc.cpp myClass1.cpp myClass2.cpp
