(function(){
var K=document;function N(){var c=K.cookie,a=Math.round((new Date).getTime()/1000),b=c.indexOf("__utma=")>-1,d=c.indexOf("__utmb=")>-1,h=c.indexOf("__utmc=")>-1,f,g={};if(b){f=c.split("__utma=")[1].split(";")[0].split(".");g.sid=(!d||!h?a:f[4])+"";g.vid=f[1]+"."+f[2];g.from_cookie=true}else{g.sid=window&&window.gaGlobal&&window.gaGlobal.sid?window.gaGlobal.sid:a+"";g.vid=window&&window.gaGlobal&&window.gaGlobal.vid?window.gaGlobal.vid:Math.round(Math.random()*2147483647)+"."+a;g.from_cookie=false}g.hid=
window&&window.gaGlobal&&window.gaGlobal.hid?window.gaGlobal.hid:Math.round(Math.random()*2147483647);window.gaGlobal=g;return g}function n(c){return c!=null?'"'+c+'"':'""'}function L(c){if(typeof encodeURIComponent=="function"){return encodeURIComponent(c)}else{return escape(c)}}function e(c,a){if(a){window.google_ad_url+="&"+c+"="+a}}function i(c,a){if(a){e(c,L(a))}}function m(c,a,b){if(a&&typeof a=="object"){a=a[b%a.length]}e("color_"+c,a)}function P(c,a){var b=c.screen,d=navigator.javaEnabled(),
h=-a.getTimezoneOffset();if(b){e("u_h",b.height);e("u_w",b.width);e("u_ah",b.availHeight);e("u_aw",b.availWidth);e("u_cd",b.colorDepth)}e("u_tz",h);e("u_his",history.length);e("u_java",d);if(navigator.plugins){e("u_nplug",navigator.plugins.length)}if(navigator.mimeTypes){e("u_nmime",navigator.mimeTypes.length)}}function v(c){c=c.toLowerCase();if(c&&c.substring(0,3)!="ca-"){c="ca-"+c}return c}function Z(c,a,b,d){b=b.substring(0,2000);b=b.replace(/%\w?$/,"");if(c.google_ad_output=="js"&&(c.google_ad_request_done||
c.google_radlink_request_done)){a.write('<script language="JavaScript1.1" src='+n(b)+"><\/script>")}else if(c.google_ad_output=="html"){if(c.name!="google_ads_frame"){if(d!=null){a.write('<div id="'+d+'">')}a.write('<iframe name="google_ads_frame" width='+n(c.google_ad_width)+" height="+n(c.google_ad_height)+" frameborder="+n(c.google_ad_frameborder)+" src="+n(b)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">');a.write("</iframe>");if(d!=null){a.write("</div>")}}}else if(c.google_ad_output==
"textlink"){a.write('<script language="JavaScript1.1" src='+n(b)+"><\/script>")}}function W(c){var a=null;c.google_ad_frameborder=a;c.google_ad_format=a;c.google_page_url=a;c.google_language=a;c.google_gl=a;c.google_country=a;c.google_region=a;c.google_city=a;c.google_hints=a;c.google_safe=a;c.google_encoding=a;c.google_ad_output=a;c.google_max_num_ads=a;c.google_ad_channel=a;c.google_contents=a;c.google_alternate_ad_url=a;c.google_alternate_color=a;c.google_color_bg=a;c.google_color_text=a;c.google_color_link=
a;c.google_color_url=a;c.google_color_border=a;c.google_color_line=a;c.google_reuse_colors=a;c.google_adtest=a;c.google_kw_type=a;c.google_kw=a;c.google_num_radlinks=a;c.google_max_radlink_len=a;c.google_rl_filtering=a;c.google_rl_mode=a;c.google_rt=a;c.google_rl_dest_url=a;c.google_num_radlinks_per_unit=a;c.google_ad_type=a;c.google_image_size=a;c.google_feedback=a;c.google_skip=a;c.google_page_location=a;c.google_referrer_url=a;c.google_ad_region=a;c.google_ad_section=a;c.google_bid=a;c.google_cpa_choice=
a;c.google_cust_age=a;c.google_cust_gender=a;c.google_cust_interests=a;c.google_cust_id=a;c.google_cust_job=a;c.google_cust_u_url=a;c.google_cust_l=a;c.google_cust_lh=a;c.google_cust_ch=a;c.google_ed=a;c.google_targeting=a;c.google_ad_host=a;c.google_ad_slot=a;c.google_ad_override=a;c.google_ui_features=a;c.google_only_ads_with_video=a;c.google_disable_video_autoplay=a}function I(c){var a=null,b=window,d=document,h=new Date,f=h.getTime(),g=b.google_ad_format;if(b.google_cpa_choice!=a){b.google_ad_url=
"http://pagead2.googlesyndication.com/cpa/ads?";b.google_ad_url+="client="+escape(v(b.google_ad_client));b.google_ad_region="_google_cpa_region_";e("cpa_choice",b.google_cpa_choice);if(typeof d.characterSet!="undefined"){i("oe",d.characterSet)}else if(typeof d.charset!="undefined"){i("oe",d.charset)}}else{b.google_ad_url="http://pagead2.googlesyndication.com/pagead/ads?";b.google_ad_url+="client="+escape(v(b.google_ad_client))}e("host",b.google_ad_host);var j=b.google_num_slots_by_client,D=b.google_num_slots_by_channel,
l=b.google_prev_ad_formats_by_region;if(b.google_ad_region==a&&b.google_ad_section!=a){b.google_ad_region=b.google_ad_section}var k=b.google_ad_region==a?"":b.google_ad_region,s=false;if(g){s=g.indexOf("_0ads")>0}else if(b.google_ad_output!="html"&&b.google_num_radlinks>0){s=true}if(s){if(b.google_num_0ad_slots){b.google_num_0ad_slots=b.google_num_0ad_slots+1}else{b.google_num_0ad_slots=1}if(b.google_num_0ad_slots>3){return false}}else if(b.google_cpa_choice==a){if(b.google_num_ad_slots){b.google_num_ad_slots=
b.google_num_ad_slots+1}else{b.google_num_ad_slots=1}if(b.google_num_slots_to_rotate){l[k]=a;if(b.google_num_slot_to_show==a){b.google_num_slot_to_show=f%b.google_num_slots_to_rotate+1}if(b.google_num_slot_to_show!=b.google_num_ad_slots){return false}}else if(b.google_num_ad_slots>3&&k==""){return false}}e("dt",h.getTime());e("hl",b.google_language);if(b.google_country){e("gl",b.google_country)}else{e("gl",b.google_gl)}e("gr",b.google_region);i("gcs",b.google_city);i("hints",b.google_hints);e("adsafe",
b.google_safe);e("oe",b.google_encoding);e("lmt",b.google_last_modified_time);i("alternate_ad_url",b.google_alternate_ad_url);e("alt_color",b.google_alternate_color);e("skip",b.google_skip);e("targeting",b.google_targeting);var p=b.google_ad_client;if(!j[p]){j[p]=1;j.length+=1}else{j[p]+=1}if(l[k]){i("prev_fmts",l[k].toLowerCase());if(j.length>1){e("slot",j[p])}}if(g&&!b.google_ad_slot){i("format",g.toLowerCase());if(l[k]){l[k]=l[k]+","+g}else{l[k]=g}}e("num_ads",b.google_max_num_ads);e("output",
c!=a?c:b.google_ad_output);e("adtest",b.google_adtest);if(b.google_ad_slot){e("slotname",b.google_ad_slot)}i("correlator",b.google_correlator);if(b.google_ad_channel){var y=b.google_ad_channel;i("channel",y);var z="",A=y.split("+");for(var t=0;t<A.length;t++){var u=A[t];if(!D[u]){D[u]=1}else{z+=u+"+"}}i("pv_ch",z)}i("url",b.google_page_url);m("bg",b.google_color_bg,f);m("text",b.google_color_text,f);m("link",b.google_color_link,f);m("url",b.google_color_url,f);m("border",b.google_color_border,f);
m("line",b.google_color_line,f);if(b.google_reuse_colors)e("reuse_colors",1);else e("reuse_colors",0);e("kw_type",b.google_kw_type);i("kw",b.google_kw);i("contents",b.google_contents);e("num_radlinks",b.google_num_radlinks);e("max_radlink_len",b.google_max_radlink_len);e("rl_filtering",b.google_rl_filtering);e("rl_mode",b.google_rl_mode);e("rt",b.google_rt);i("rl_dest_url",b.google_rl_dest_url);e("num_radlinks_per_unit",b.google_num_radlinks_per_unit);e("ad_type",b.google_ad_type);e("image_size",
b.google_image_size);e("region",b.google_ad_region);e("feedback_link",b.google_feedback);i("ref",b.google_referrer_url);i("loc",b.google_page_location);e("bid",b.google_bid);e("cust_age",b.google_cust_age);e("cust_gender",b.google_cust_gender);e("cust_interests",b.google_cust_interests);e("cust_id",b.google_cust_id);e("cust_job",b.google_cust_job);e("cust_u_url",b.google_cust_u_url);e("cust_l",b.google_cust_l);e("cust_lh",b.google_cust_lh);e("cust_ch",b.google_cust_ch);e("ed",b.google_ed);i("ui",
b.google_ui_features);i("only_ads_with_video",b.google_only_ads_with_video);i("disable_video_autoplay",b.google_disable_video_autoplay);if(G(b,d)&&d.body){var B=d.body.scrollHeight,C=d.body.clientHeight;if(C&&B){i("cc",Math.round(C*100/B))}}N();e("ga_vid",b.gaGlobal.vid);e("ga_sid",b.gaGlobal.sid);e("ga_hid",b.gaGlobal.hid);e("ga_fc",b.gaGlobal.from_cookie);i("ga_wpids",b.google_analytics_webpropids);e("google_ad_override",b.google_ad_override);e("flash",b.google_flash_version);P(b,h);return true}
function H(){var c=window,a=document,b=false;if(Q(c.google_ad_output,c.google_ad_client)&&!Y()){b=true}var d=b?"json_html":null;if(!I(d)){return}if(!b){Z(c,a,c.google_ad_url,null)}else{V()}W(c)}function M(c,a,b){H();return true}function G(c,a){return c.top.location==a.location}function F(c,a){var b=a.documentElement;if(G(c,a))return false;if(c.google_ad_width&&c.google_ad_height){var d=1,h=1;if(c.innerHeight){d=c.innerWidth;h=c.innerHeight}else if(b&&b.clientHeight){d=b.clientWidth;h=b.clientHeight}else if(a.body){d=
a.body.clientWidth;h=a.body.clientHeight}if(h>2*c.google_ad_height||d>2*c.google_ad_width){return false}}return true}function R(c){var a=window,b=document,d=b.location,h=b.referrer,f=null,g=a.onerror;a.onerror=c;if(a.google_ad_frameborder==f){a.google_ad_frameborder=0}if(a.google_ad_output==f){a.google_ad_output="html"}if(a.google_ad_format==f&&a.google_ad_output=="html"){a.google_ad_format=a.google_ad_width+"x"+a.google_ad_height}if(a.google_page_url==f){a.google_page_url=h;if(!F(a,b)){a.google_page_url=
d;a.google_last_modified_time=Date.parse(b.lastModified)/1000;a.google_referrer_url=h}}else{a.google_page_location=h;if(!F(a,b)){a.google_page_location=d}}if(a.google_num_slots_by_channel==f){a.google_num_slots_by_channel=[]}if(a.google_num_slots_by_client==f){a.google_num_slots_by_client=[]}if(a.google_prev_ad_formats_by_region==f){a.google_prev_ad_formats_by_region=[]}if(a.google_correlator==f){a.google_correlator=(new Date).getTime()}if(a.google_adslot_loaded==f){a.google_adslot_loaded={}}if(a.google_adContentsBySlot==
f){a.google_adContentsBySlot={}}if(a.google_flash_version==f){a.google_flash_version=J().toString()}a.onerror=g}function o(c){if(c in q){return q[c]}return q[c]=navigator.userAgent.toLowerCase().indexOf(c)!=-1}var q={};function r(){return o("msie")&&!window.opera}function w(){return o("safari")}function O(){var c=navigator.userAgent,a=c.indexOf("MSIE ");if(a==-1){return 0}else{return parseFloat(c.substring(a+5,c.indexOf(";",a)))}}function Y(){if(r()){var c=O();return c<=5}else if(o("firefox")){var a=
navigator.userAgent.indexOf("Firefox")+8,b=parseInt(navigator.userAgent.charAt(a)),d=navigator.userAgent.slice(a);return b<1}else if(w()){var a=navigator.userAgent.indexOf("Safari")+7,d=navigator.userAgent.slice(a),h=parseInt(d);return h<412}else if(window.opera!=null){var a=navigator.userAgent.indexOf("Opera")+6,d=navigator.userAgent.slice(a),b=parseInt(d);return b<9}else if(!r()&&!w()&&o("mozilla")){var a=navigator.userAgent.indexOf("Netscape")+9,d=navigator.userAgent.slice(a),b=parseInt(d);return b<
7}else{return true}}function Q(c,a){var b=window;if(c!="html"){return false}if(b.google_cpa_choice!=null){return false}var d={};d["ca-pub-8954402009499768"]=true;d["ca-pub-7027491298716603"]=true;d["ca-pub-8091322912406003"]=true;d["ca-pub-2996719119399840"]=true;d["ca-pub-2071992140100640"]=true;d["ca-pub-8887131281660947"]=true;d["ca-pub-9425162160615080"]=true;d["ca-pub-0636374063477327"]=true;d["ca-pub-4840216691262122"]=true;d["ca-pub-6655028338425523"]=true;d["ca-pub-9500441424288493"]=true;
d["ca-pub-7869439110764952"]=true;d["ca-pub-6682766817737063"]=true;d["ca-pub-3645353514626463"]=true;return d[v(a)]!=null}function V(){var c=window;e("impl","s");e("callback","_google_setAdContentsBySlotForSync");document.write("<script src = '"+c.google_ad_url+"'><\/script>")}function X(c){var a=document.getElementById("google_flash_div");if(a!=null){a.style.height=c+"px"}var b=document.getElementById("google_flash_obj");if(b!=null){b.height=c}var d=document.getElementById("google_flash_embed");
if(d!=null){d.height=c}}window.google_createDivWithContent=function(c){var a=window,b="google_ads_div_"+c,d="<div id="+b+">",h=a.google_adContentsBySlot[c];if(h==null){return}d+=h._html_;d+="\n</div>\n";document.write(d)};window.google_createDOMIframe=function(c,a,b,d){var h=document.getElementsByTagName("script"),f=h[h.length-1],g=document.createElement("iframe");g.id="google_ads_iframe_"+c;g.width=a;g.height=b;g.vspace=0;g.hspace=0;g.allowTransparency="true";g.scrolling="no";g.marginWidth=0;g.marginHeight=
0;g.frameBorder=0;g.style.border=0;f.parentNode.appendChild(g);g.contentWindow.document.write(d);g.contentWindow.document.close()};window.google_createiframe=function(c,a,b,d,h){var f="google_ads_div_"+c,g="google_ads_iframe_"+c,j="<div id="+f+">";j+="<iframe id="+g+' width="'+d+'" height="'+h+'" vspace="0" hspace="0" allowtransparency="true" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" style="border:0px;" src="'+a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,
"&quot;")+'"';j+=' onload="'+b+'"';j+="></iframe></div>";document.write(j)};var x="google_ads_iframe_".length;function E(c){var a=c.getAttribute("id"),b=a.substr(x,a.length-x);return b}function S(c){var a=window,b=E(c),d=a.google_adslot_loaded[b];if(d){return}a.google_adslot_loaded[b]=true;var h=window.google_adContentsBySlot[b],f=c.contentWindow?c.contentWindow.document:c.contentDocument;if(f==null){if(document.implementation&&document.implementation.createDocument){f=document.implementation.createDocument("",
b,null)}else if(typeof ActiveXObject!=undefined){f=new ActiveXObject("Msxml.DOMDocument")}else{return}}f.open("text/html","replace");f.write(h._html_);f.close()}window._google_syncAdSlotLoaded=function(c){var a=E(c);S(c)};window._google_setAdContentsBySlotForSync=function(c){var a=window;for(var b in c){var d=c[b];a.google_adContentsBySlot[b]=d;if(d==null||d._empty_){}else if(d._expandable_){a.google_createDivWithContent(b)}else{if(navigator.userAgent.indexOf("MSIE ")>0){a.google_adslot_loaded[b]=
false;var h="window._google_syncAdSlotLoaded(this);";a.google_createiframe(b,"about:blank",h,d._width_,d._height_)}else{a.google_createDOMIframe(b,d._width_,d._height_,d._html_)}}}};function U(c){var a={},b=c.split("?"),d=b[b.length-1].split("&");for(var h=0;h<d.length;h++){var f=d[h].split("=");if(f[0]){try{a[f[0].toLowerCase()]=f.length>1?(window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1])):""}catch(g){}}}return a}function T(){var c=window,a=U(document.URL);if(a.google_ad_override){c.google_ad_override=
a.google_ad_override}}function J(){var c=0;if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description){c=a.description.replace(/([a-zA-Z]|\s)+/,"").split(".")[0]}}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){c=3;var b=1;while(b){try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(c+1));c++}catch(d){b=null}}}else if(r()){try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
c=6;b.AllowScriptAccess="always"}catch(d){if(c==6){return c}}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(b!=null){c=b.GetVariable("$version").split(" ")[1].split(",")[0]}}return c}window.google_resize_flash_ad=X;T();R(M);H();
})()