######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 2 09:30:54 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cube.h
SOURCES += cube.cpp main.cpp
